plugins {
    id 'java'
    id 'war'
    id 'org.springframework.boot' version '4.0.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

// 빌드 날짜를 버전에 포함 (예: 20251211-dev)
def formattedDate = new Date().format('yyyyMMdd')

group = 'com.dakgu'
version = "${formattedDate}-dev"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    JJWT_VERSION = "0.12.6"
}

dependencies {
    // --- [Web & Core] ---
    implementation 'org.springframework.boot:spring-boot-starter-web'           // 웹 앱 개발 필수 모듈 (Tomcat, MVC)
    implementation 'org.springframework.boot:spring-boot-starter-validation'    // 데이터 유효성 검사
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'       // 외장 배포 시 필요한 톰캣 런타임
    developmentOnly 'org.springframework.boot:spring-boot-devtools'             // 개발 편의 도구

    // --- [Security & Auth] ---
    implementation 'org.springframework.boot:spring-boot-starter-security'      // 스프링 시큐리티
    implementation "io.jsonwebtoken:jjwt-api:${JJWT_VERSION}"                   // JWT 토큰 API
    runtimeOnly "io.jsonwebtoken:jjwt-impl:${JJWT_VERSION}"                     // JWT 토큰 구현체
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:${JJWT_VERSION}"                  // JWT JSON 처리를 위한 어댑터

    // --- [Data & Database] ---
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'      // JPA 스타터
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'    // Redis 연동
    implementation 'com.mysql:mysql-connector-j:8.4.0'                          // MySQL 드라이버
    implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.12.0'  // 쿼리 파라미터 로그 출력 도구

    // --- [Messaging & Network] ---
    implementation 'org.springframework.boot:spring-boot-starter-websocket'     // 웹소켓 및 STOMP 프로토콜 지원
    implementation 'com.github.mwiede:jsch:2.27.2'                              // SSH 원격 접속 라이브러리

    // --- [Utilities] ---
    implementation 'tools.jackson.core:jackson-databind:3.0.3'                  // JSON 데이터 바인딩
    compileOnly 'org.projectlombok:lombok'                                      // 코드 간소화 라이브러리
    annotationProcessor 'org.projectlombok:lombok'                              // 롬복 어노테이션 프로세서

    // --- [Testing] ---
    testImplementation 'org.springframework.boot:spring-boot-starter-test'      // 스프링 부트 통합 테스트
    testImplementation 'org.springframework.security:spring-security-test'      // 시큐리티 관련 테스트 지원
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'                // JUnit 테스트 런처
}