driverlist=com.mysql.cj.jdbc.Driver
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime)|%(executionTime)ms|%(category)|%(sqlSingleLine)
includeBindParameters=true
autoflush=true
dateformat=yy.MM.dd HH:mm:ss
excludecategories=result,resultset,debug,info,batch,commit
stacktrace=false
outagedetection=true
outagedetectioninterval=500
# sqlexcludepattern=.*information_schema.*|SELECT\\s+1