# P6Spy ?? ?? (src/main/resources/spy.properties)

# ?? ???? JDBC ???? (p6spy? ???? ? ????? ??)
driverlist=com.mysql.cj.jdbc.Driver

# ??? SLF4J? ????? ??
appender=com.p6spy.engine.spy.appender.Slf4JLogger

# ?? ??: SingleLineFormat? ??? ??? ?? ? ?? ??
logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat

# PreparedStatement ??? ? ?? ??
includeBindParameters=true

# ?? flush (??? ????? ??)
autoflush=true

excludecategories=info,debug,result,batch